#pragma kernel StrokeCompute

Texture2D<float4> _MainTex;

RWStructuredBuffer<float4> _BrushData;

RWTexture2D<float4> _Result;

float4 _TexSize;
float4 _Mouse;

#define BRUSH_SIZE 20.0
#define STROKE_LENGTH 600.0

float rand(float2 n) { 
                return frac(sin(dot(n, float2(12.9898, 4.1414))) * 43758.5453);
}

float noise(float2 p) {
    float2 ip = floor(p);
    float2 u = frac(p);
    u = u*u*(3.0-2.0*u);
    
    float res = lerp(
        lerp(rand(ip), rand(ip+float2(1.0,0.0)), u.x),
        lerp(rand(ip+float2(0.0,1.0)), rand(ip+float2(1.0,1.0)), u.x), u.y);
    return res*res;
}

[numthreads(8, 8, 1)]
void StrokeCompute (uint3 id : SV_DispatchThreadID)
{
    float2 fragCoord = float2(id.xy);
    float2 uv = (fragCoord + 0.5) * _TexSize.zw;
    float4 brushData =  _BrushData[0];
    float brushStrength = brushData.z;


    float3 col = _MainTex[id.xy].rgb;
    float2 dirVec = normalize(_Mouse.xy - brushData.xy);
    dirVec = float2(dirVec.y, -dirVec.x);
    float vd = dot(fragCoord, dirVec);

    float brushStregthRamp = clamp(sin(brushStrength * 3.1415926), 0.0, 1.0);

    for(int i=0; i < 20; i++) {
        float2 mPos = lerp(_Mouse.xy, brushData.xy, float(i) / 20.0);
        float d = 1.0 - smoothstep(0.0, 1.0, distance(fragCoord, mPos) / BRUSH_SIZE / brushStregthRamp);
        d *= smoothstep(0.2, 1.0, (noise(fragCoord - mPos) + 0.75) / 5.0) * 10.0;
        float bd = 1.0 - smoothstep(0.0, 1.0, distance(fragCoord, mPos) / BRUSH_SIZE / brushStregthRamp / 1.5  );
        
        bd *= smoothstep(0.1, 1.0, (noise(float2(brushStrength * 20.0, 0.0) + (fragCoord - mPos) / 2.0) + 0.0) / 5.0) * 10.0;               
        col += float3(bd,bd,bd) + float3(d,d,d);
    }

    brushStrength -= distance(_Mouse.xy, brushData.xy) / STROKE_LENGTH;
    if(_Mouse.z != brushData.w) {
        brushStrength = _Mouse.z;
    }
    brushStrength = clamp(brushStrength, 0.0, 1.0);
    float4 newBrushData = float4(_Mouse.xy, brushStrength, _Mouse.z);
    
    if(id.x == 0 && id.y == 0){
        _BrushData[0] = newBrushData;
    }

    _Result[id.xy] = float4(col, 1.0);
}